# Simplified Cloud Build configuration
steps:
  # Build and deploy directly to Cloud Run without intermediate registry
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'terrain-generator'
      - '--source=.'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=2021'
      - '--memory=1Gi'
      - '--cpu=1'
      - '--max-instances=10'
      - '--set-env-vars=NODE_ENV=production'

# Enable detailed logging
options:
  logging: LEGACY

timeout: '1200s'