# Cloud Build configuration for long-running terrain jobs
steps:
  # Build and deploy to Cloud Run with extended timeouts
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'terrain-generator'
      - '--source=.'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=2021'
      - '--timeout=3600'           # 1 hour timeout (max for Cloud Run)
      - '--memory=8Gi'             # 8GB memory for large datasets
      - '--cpu=4'                  # 4 CPUs for faster processing
      - '--max-instances=3'        # Allow scaling but limit costs
      - '--min-instances=0'        # Scale to zero when not used
      - '--concurrency=1'          # Only 1 request per instance
      - '--set-env-vars=NODE_ENV=production,MAX_RESOLUTION=5000'

# Use NONE logging to avoid service account issues
options:
  logging: NONE

timeout: '1200s'